services:
  web:
    build:
      context: .
      args:
        NEXT_PUBLIC_SITE_URL: https://csti-challenge.orlando-rojas.com
    image: ghcr.io/orlando-rojas/csti-challenge:latest
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_SITE_URL: https://csti-challenge.orlando-rojas.com
      SITE_INDEXABLE: "true"
      FAKESTORE_API_URL: https://csti-challenge-fakestore.orlando-rojas.com
      LOG_LEVEL: info
    volumes:
      - csti-next-cache:/app/.next/cache
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.csti-challenge-web.rule=Host(`csti-challenge.orlando-rojas.com`)
      - traefik.http.routers.csti-challenge-web.entrypoints=web
      - traefik.http.routers.csti-challenge-web.service=csti-challenge-web
      - traefik.http.services.csti-challenge-web.loadbalancer.server.port=3000
    networks:
      - dokploy-network

volumes:
  csti-next-cache:

networks:
  dokploy-network:
    external: true
